language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install gnuplot

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install gnuplotlib
  - pip install travis-sphinx numpydoc ipython sphinxcontrib-fulltoc
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - ribocop
  - travis-sphinx build --source=$TRAVIS_BUILD_DIR/docs

after_success:
  - travis-sphinx deploy

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: saketkc
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: saketkc/ribocop
    condition: $TRAVIS_PYTHON_VERSION == "2.7"
